# Generated by Django 3.1.5 on 2021-06-27 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='photo',
            field=models.ImageField(default='', upload_to='photo/%Y/%m/%d/'),
            preserve_default=False,
        ),
    ]
